# Generated by Django 5.2.7 on 2026-05-01 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='transaction_ref_id',
        ),
    ]
