# Generated by Django 5.2.7 on 2026-05-02 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_remove_order_transaction_ref_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='funding',
            name='used_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
