# Generated by Django 5.2.7 on 2025-11-28 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_alter_order_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funding',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fundings', to='lms.userprofile'),
        ),
    ]
