# Generated by Django 5.2.7 on 2026-05-03 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0003_funding_used_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='sponsor_used',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
