# Generated by Django 5.2.7 on 2025-11-28 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0003_alter_funding_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='funding',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
