# Generated by Django 5.2.7 on 2026-05-04 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0004_order_sponsor_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='funding',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fundings', to='lms.order'),
        ),
    ]
