# Generated by Django 5.2.7 on 2025-12-04 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0004_funding_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discussion',
            name='course',
        ),
        migrations.RemoveField(
            model_name='discussion',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Discussion',
        ),
    ]
