# Generated by Django 5.2.7 on 2026-04-29 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0005_remove_discussion_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='images/pic1.jpg', upload_to='profile_images/'),
        ),
    ]
